micronaut:
  application:
    name: example-jooq
jackson:
  bean-introspection-module: true
---
datasources:
  default:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    schema: ${DATABASE_SCHEMA}
---
flyway:
  datasources:
    default:
      enabled: true
