micronaut:
  application:
    name: example-jooq
jackson:
  bean-introspection-module: true
---
datasources:
  default:
    url: 'jdbc:postgresql://127.0.0.1:5432/devDb'
    username: devDb
    password: devDb
    schema: public
---
flyway:
  datasources:
    default:
      enabled: true
